version: "2"
pipelines:
  otel-trace-pipeline:
    source:
      otel_trace_source:
        ssl: false
        port: 21890
    processor:
      - otel_trace_raw:
      - otel_trace_group:
    sink:
      - opensearch:
          hosts: ["http://opensearch:9200"]
          index_type: trace-analytics-raw
          username: ""
          password: ""
