version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:2.8.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_SECURITY_DISABLED=true
      - plugins.security.ssl.http.enabled=false
      - plugins.security.audit.config.enable_transport=true
      - plugins.security.allow_unsafe_democertificates=true
      - plugins.security.allow_default_init_securityindex=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - osnet

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    networks:
      - osnet

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - 4317:4317   # OTLP gRPC receiver
      - 4318:4318   # OTLP HTTP receiver
    depends_on:
      - opensearch
    networks:
      - osnet

  data-prepper:
    image: opensearchproject/data-prepper:2.9.0
    container_name: data-prepper
    volumes:
      - ./data-prepper-config.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
    ports:
      - "21890:21890" # OTLP receiver
    depends_on:
      - opensearch
    networks:
      - osnet     

networks:
  osnet:
    driver: bridge
